build:
  image: xataz/docker-client:1.12.5
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /Users/flemzord/.docker/config.json:/home/docker/.docker/config.json
    - /Users/flemzord/.docker/config.json:/root/.docker/config.json
  environment:
    - UID=1000
    - GID=1000
  commands:
    - chmod +x build.sh
    - ./build.sh push
